import { pgEnum, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'

// Source of truth for the database structure (see docs/RESTRUCTURE_PLAN.md).
// Consumed by drizzle-kit only — the site itself talks to Supabase via supabase-js,
// and the public RSVP flow goes through the RPCs defined in the rls_and_rpcs migration.

export const guestStatus = pgEnum('guest_status', ['pending', 'accepted', 'declined'])

export const guests = pgTable('guests', {
  id: uuid('id').primaryKey().defaultRandom(),
  /** Short unguessable code used in invite links (?g=<token>). Auto-generated by trigger when omitted. */
  token: text('token').notNull().unique(),
  fullName: text('full_name').notNull(),
  /** Optional, digits with country code (e.g. 51987654321) — enables wa.me deep links from the manage page. */
  phone: text('phone'),
  /** Optional free-text grouping, e.g. "Familia Pérez" — for filtering/sending family links together. */
  groupLabel: text('group_label'),
  status: guestStatus('status').notNull().default('pending'),
  /** Guest's optional message to the couple, captured with their RSVP. */
  message: text('message'),
  respondedAt: timestamp('responded_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

/** Allowlist for the manage page. Rows are seeded by migration / added via SQL, never via the API. */
export const admins = pgTable('admins', {
  email: text('email').primaryKey(),
})
