// Bulk-import/update guests from a CSV export (e.g. the old Google Sheet RSVP responses).
//
//   npm run db:import -- ruta/al/archivo.csv          # apply changes
//   npm run db:import -- ruta/al/archivo.csv --dry    # preview, write nothing
//
// Header detection is flexible (Spanish/English aliases; accents and punctuation ignored,
// so "¿Asistirás?" matches). Only a name column is required. Status values like
// "Sí, ¡con gusto!" / "Con pena, no podré" map to accepted/declined. Matching is by
// normalized full name:
//   - new name  -> INSERT (token auto-generated by the DB trigger)
//   - existing  -> fills phone/group/message if provided; never downgrades a non-pending
//                  status already registered through the site.
import { readFileSync } from 'node:fs'
import postgres from 'postgres'

const args = process.argv.slice(2)
const dry = args.includes('--dry')
const file = args.find((a) => !a.startsWith('--'))
if (!file) {
  console.error('Uso: npm run db:import -- archivo.csv [--dry]')
  process.exit(1)
}
if (!process.env.DATABASE_URL) {
  console.error('Falta DATABASE_URL (revisa .env)')
  process.exit(1)
}

const stripAccents = (s) => String(s ?? '').normalize('NFD').replace(/[̀-ͯ]/g, '')

/** For guest names: accent-insensitive, lowercase. */
const norm = (s) => stripAccents(s).toLowerCase().trim()

/** For CSV headers: additionally drop punctuation ("¿Asistirás?" -> "asistiras"). */
const normHeader = (s) => norm(s).replace(/[^a-z0-9 _]/g, '').trim()

// Minimal RFC4180 parser (quotes, escaped quotes, CRLF). Returns array of rows.
function parseCsv(text) {
  const src = text.replace(/^﻿/, '')
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false
  for (let i = 0; i < src.length; i++) {
    const c = src[i]
    if (inQuotes) {
      if (c === '"') {
        if (src[i + 1] === '"') {
          field += '"'
          i++
        } else inQuotes = false
      } else field += c
    } else if (c === '"') inQuotes = true
    else if (c === ',') {
      row.push(field)
      field = ''
    } else if (c === '\n' || c === '\r') {
      if (c === '\r' && src[i + 1] === '\n') i++
      row.push(field)
      if (row.some((f) => f.trim() !== '')) rows.push(row)
      row = []
      field = ''
    } else field += c
  }
  row.push(field)
  if (row.some((f) => f.trim() !== '')) rows.push(row)
  return rows
}

const HEADER_ALIASES = {
  full_name: ['nombre', 'nombre completo', 'name', 'full name', 'full_name', 'invitado'],
  phone: ['telefono', 'whatsapp', 'celular', 'phone', 'numero', 'tel'],
  group_label: ['grupo', 'group', 'familia'],
  status: ['estado', 'status', 'asistencia', 'asistira', 'asistiras', 'respuesta', 'attending', 'confirmacion'],
  message: ['mensaje', 'message', 'comentario', 'notas', 'mensaje para los novios'],
}

function mapStatus(raw) {
  const v = norm(raw)
  if (!v) return 'pending'
  if (/(pena|no podr|no asist|no ire|no voy|declin|rechaz)/.test(v) || v === 'no') return 'declined'
  if (/(gusto|acept|confirm|asist|si|yes)/.test(v)) return 'accepted'
  return 'pending'
}

function mapPhone(raw) {
  const d = String(raw ?? '').replace(/\D/g, '')
  if (!d) return null
  // Peruvian mobiles are 9 digits starting with 9 — add the country code if missing.
  return /^9\d{8}$/.test(d) ? '51' + d : d
}

const rows = parseCsv(readFileSync(file, 'utf8'))
if (rows.length < 2) {
  console.error('El CSV no tiene filas de datos.')
  process.exit(1)
}

const header = rows[0].map(normHeader)
const idx = {}
for (const [field, aliases] of Object.entries(HEADER_ALIASES)) {
  const i = header.findIndex((h) => aliases.includes(h))
  if (i !== -1) idx[field] = i
}
if (idx.full_name === undefined) {
  console.error(`No encontré la columna de nombre. Encabezados detectados: ${rows[0].join(' | ')}`)
  process.exit(1)
}
console.log(
  'Columnas detectadas:',
  Object.entries(idx)
    .map(([f, i]) => `${f}←"${rows[0][i]}"`)
    .join(', '),
)

const sql = postgres(process.env.DATABASE_URL, { ssl: 'require', max: 1, connect_timeout: 15 })
try {
  const existing = await sql`
    select id, full_name, phone, group_label, status, message, responded_at from public.guests`
  const byName = new Map(existing.map((g) => [norm(g.full_name), g]))

  let inserted = 0
  let updated = 0
  let unchanged = 0
  let skipped = 0

  for (const row of rows.slice(1)) {
    const name = String(row[idx.full_name] ?? '').trim()
    if (!name) {
      skipped++
      continue
    }
    const phone = idx.phone !== undefined ? mapPhone(row[idx.phone]) : null
    const group = idx.group_label !== undefined ? String(row[idx.group_label] ?? '').trim() || null : null
    const status = idx.status !== undefined ? mapStatus(row[idx.status]) : 'pending'
    const message = idx.message !== undefined ? String(row[idx.message] ?? '').trim().slice(0, 500) || null : null

    const ex = byName.get(norm(name))
    if (!ex) {
      const rec = {
        full_name: name,
        phone,
        group_label: group,
        status,
        message,
        responded_at: status !== 'pending' ? new Date() : null,
      }
      if (dry) console.log(`[dry] INSERT  ${name}  (${status}${phone ? ', ' + phone : ''}${group ? ', ' + group : ''})`)
      else await sql`insert into public.guests ${sql(rec)}`
      byName.set(norm(name), { ...rec, id: 'new' })
      inserted++
      continue
    }

    const patch = {}
    if (phone && phone !== ex.phone) patch.phone = phone
    if (group && group !== ex.group_label) patch.group_label = group
    if (message && !ex.message) patch.message = message
    // Never downgrade an answer already registered through the site.
    if (status !== 'pending' && ex.status === 'pending') {
      patch.status = status
      patch.responded_at = new Date()
    }
    if (Object.keys(patch).length === 0) {
      unchanged++
      continue
    }
    if (dry) console.log(`[dry] UPDATE  ${name}  → ${Object.keys(patch).join(', ')}`)
    else await sql`update public.guests set ${sql(patch)} where id = ${ex.id}`
    updated++
  }

  console.log(
    `${dry ? '[dry] ' : ''}Resultado: ${inserted} insertados, ${updated} actualizados, ${unchanged} sin cambios, ${skipped} sin nombre (omitidos).`,
  )
} finally {
  await sql.end()
}
